webtalk_init -webtalk_dir /home/aitesam961/GitHub/bi-tribble/asmcvd_xp/asmcvd_xp.sim/sim_1/behav/xsim/xsim.dir/asmcvd_xp_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Feb  1 10:56:16 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "ac4dd925-6971-4e10-8211-c9e1db1a7e32" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "38a80270e3ba4ebd931e5ac6a66b420e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "56" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 23.10" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "4021.802 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key SystemVerilog -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key File_Counter -value "6" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "30 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "3 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "47" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "9" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "0.83_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "206472_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2018330700 -regid "" -xml /home/aitesam961/GitHub/bi-tribble/asmcvd_xp/asmcvd_xp.sim/sim_1/behav/xsim/xsim.dir/asmcvd_xp_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/aitesam961/GitHub/bi-tribble/asmcvd_xp/asmcvd_xp.sim/sim_1/behav/xsim/xsim.dir/asmcvd_xp_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/aitesam961/GitHub/bi-tribble/asmcvd_xp/asmcvd_xp.sim/sim_1/behav/xsim/xsim.dir/asmcvd_xp_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
